### ISSUE TITLE
Chat client version is 1.0

### ISSUE THREAD

**Issue by scarroll32** [TwilioDevEd/sdk-starter-ruby#12]
It looks like the chat client has hit 1.0

https://www.twilio.com/docs/api/chat/sdks

Does it affect this demo, other than the library?

**Comment by jefflinwood** [comment]
Hi,

Great question - the Chat SDK has changed quite a few things between 0.12 and 1.0 - here is the Changelog if you have your own code to update:

https://www.twilio.com/docs/api/chat/changelogs/javascript

We need to update the corresponding chat code in these SDK Starter Kits to match 1.0.

Thanks!
Jeff

**Comment by jefflinwood** [comment]
Hi,

Updated in https://github.com/TwilioDevEd/sdk-starter-ruby/pull/13

Thanks!
