### ISSUE TITLE
Sample code for chat not working

### ISSUE THREAD

**Issue by scarroll32** [TwilioDevEd/sdk-starter-ruby#2]
I'm reviewing the sample Chat app

The Video conference is working, but the chat app is not. The app logs onto Twilio:
```
Logging in...
You have been assigned a random username of: terrance
Attempting to join "general" chat channel...
```
Then there is an error in the JavaScript console:

```
index.html:1 Uncaught (in promise) 
Object
body
:
Object
description
:
"Not Found"
status
:
404
__proto__
:
Object
__defineGetter__
:
__defineGetter__()
__defineSetter__
:
__defineSetter__()
__lookupGetter__
:
__lookupGetter__()
__lookupSetter__
:
__lookupSetter__()
constructor
:
Object()
hasOwnProperty
:
hasOwnProperty()
isPrototypeOf
:
isPrototypeOf()
propertyIsEnumerable
:
propertyIsEnumerable()
toLocaleString
:
toLocaleString()
toString
:
toString()
valueOf
:
valueOf()
get __proto__
:
__proto__()
set __proto__
:
__proto__()
```

**Comment by jefflinwood** [comment]
Hi, do you have a Chat Service SID in the .env file?

Thanks!

**Comment by scarroll32** [comment]
Yes, I think it is the right SID. It is called **SERVICE SID**
https://www.twilio.com/console/chat/services/account SID

No channels have been created. I don't know if it is relevant. It is also a trial account.

**Comment by jefflinwood** [comment]
If this helps, the Service SID should start with "IS", so something like ISxxxxxxxxxssss 

No problem if no channels have been created - the Javascript Chat will create a new general channel if it doesn't exist. 

I don't personally know anything about Trial vs Paid for the Chat service.

If I don't have the TWILIO_CHAT_SERVICE_SID configured in the .env, I get the same error as you get above. Does that SID appear on the home screen (http://localhost:4567/)?

**Comment by scarroll32** [comment]
Thanks @jefflinwood for your reply.

I have double checked the the Service SID, and it seems correct. I tried modifying the code, so that the createOrJoinGeneralChannel looks like this:

```javascript
  function createOrJoinGeneralChannel() {
      console.log('Creating general channel');
      chatClient.createChannel({
          uniqueName: 'general',
          friendlyName: 'General Chat Channel'
      }).then(function(channel) {
          console.log('Created general channel:');
          console.log(channel);
          generalChannel = channel;
          setupChannel();
      });
    }
```


This works! In that it creates the channel and does not error.

The creation of the promise on the getChannelByUniqueName is returning the 404.

```javascript
var promise = chatClient.getChannelByUniqueName('general')
```

 I will continue investigating.

**Comment by scarroll32** [comment]
Just to confirm I am using the correct SID, here is a screenshot
<img width="983" alt="screen shot 2017-01-08 at 14 00 07" src="https://cloud.githubusercontent.com/assets/11340230/21750063/20b5fe4e-d5ab-11e6-80e9-3cf7359c01e3.png">

**Comment by scarroll32** [comment]
Some more information. Now that the 'general' channel has been created (by modifying the code as above), when I return the code to it's original state it seems to find the channel but returns a different error. I wonder if this could be related to permissions somehow.

<img width="1395" alt="screen shot 2017-01-08 at 14 08 35" src="https://cloud.githubusercontent.com/assets/11340230/21750131/34ce9426-d5ac-11e6-8ffa-52c6be9ea832.png">

**Comment by scarroll32** [comment]
More modified code with mixed results. I am able to get the channel by sid, this works:

```
        var promise = chatClient.getChannelBySid('CH2888c5618eae42c4b448008357535a45');
```

But later the ```.join()``` method fails.

Some more modified code:

```javascript
  // Set up channel after it has been found
    function setupChannel() {
        console.log('Join the general channel');
        console.log(generalChannel.friendlyName);
        console.log(generalChannel.createdBy);
        console.log('Is join() callable: ' + generalChannel.join && generalChannel.join());

        generalChannel.join().then(function(channel) {
            print('Joined channel as '
                + '<span class="me">' + username + '</span>.', true);
        });
```

<img width="1403" alt="screen shot 2017-01-08 at 14 58 58" src="https://cloud.githubusercontent.com/assets/11340230/21750418/0abb2a3a-d5b3-11e6-87ef-6ac96602a284.png">

**Comment by scarroll32** [comment]
Happy to share my SIDs etc with support if this helps. I've opened a support ticket within Twilio.

**Comment by jefflinwood** [comment]
That's the correct place to find the Service SID - after changing things around on this, are you able to send/receive chat messages to the channel? 

Also, does Channel CH2888c5618eae42c4b448008357535a45 exist in the Channels page of that Chat Service in the console?

Support may be able to help more in this specific case, but it would be great to figure out what the problem is.

**Comment by scarroll32** [comment]
Hi @jefflinwood, no I could not get it any further than the posts above. It is connecting and able to access the channel, and see channel attributes, but it seems the function calls such as ```.join()``` are not working for me. Is it working at your end by any chance?

Thanks for your help.

**Comment by jefflinwood** [comment]
Hi,

The code is working for me as written (downloaded code from GitHub, ran bundle install, set up .env file) - just tried it out again yesterday.

One difference I can think of is that Chat is a paid service, and perhaps trial accounts can't perform paid actions with the Chat service - has Twilio Support gotten back to you?

**Comment by scarroll32** [comment]
No the support tickets are still open with no response from Twilio. 

https://www.twilio.com/console/support/tickets/821428

**Comment by jefflinwood** [comment]
Hi,

Unfortunately, I can't view your support ticket, so I don't know what's in it, but perhaps you could comment on it there to make it reappear in the support queue?

Thanks,
Jeff

**Comment by scarroll32** [comment]
OK I'll try that. Thank you.

**Comment by scarroll32** [comment]
Closed by https://github.com/TwilioDevEd/sdk-starter-ruby/commit/106067e57bb4a6f00dd19e2c2506f7c18e10d566

Thanks a lot @jefflinwood

**Comment by minhtrangvy** [comment]
@seanfcarroll Also running into this issue. Were you able to find a resolution?

**Comment by scarroll32** [comment]
It was a while ago but see the linked code in my post above
