### ISSUE TITLE
Getting an error when running chat 

### ISSUE THREAD

**Issue by cmavromoustakos** [TwilioDevEd/sdk-starter-ruby#20]
I double checked and triple checked all my keys and everything looks good. Any ideas?

    {
        "message": "The authorization with Token failed",
        "code": 2016,
        "user_error": false,
        "params": {
            "description": "Could not authenticate fpa token"
        }
    }

<img width="1276" alt="twilio_chat_quickstart" src="https://user-images.githubusercontent.com/111412/28191291-61c5fac6-67fd-11e7-9143-02816583982e.png">

**Comment by cmavromoustakos** [comment]
So I downloaded from a link in the docs which seemed to not work. But when I cloned from this repo it resolved the issues. Closing this issue.

**Comment by jefflinwood** [comment]
Hi - which link didn't work in the docs? It would be great to get that link fixed! Sorry about that, glad you got it working in the end.

**Comment by cmavromoustakos** [comment]
@jefflinwood 

https://www.twilio.com/docs/api/chat/guides/quickstart-js

<img width="761" alt="javascript_twilio_programmable_chat_quickstart_-_twilio" src="https://user-images.githubusercontent.com/111412/28282501-9e274ec2-6af8-11e7-9766-9831fb0cb43c.png">
